In [10]:
import pandas as pd
import requests
import json
from config import api_key

In [11]:
start_year = "1960"
end_year = "2022"
prod_start_year = "1970"
prod_end_year = "2022"
#Link to number of units of nuclear generators by year.
opUnitsURL = f"https://api.eia.gov/v2/total-energy/data/?api_key={api_key}&frequency=annual&data[0]=value&facets[msn][]=NUOUPUS&start={start_year}&end={end_year}&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=100"
nuclProURL = f"https://api.eia.gov/v2/total-energy/data/?api_key={api_key}&frequency=annual&data[0]=value&facets[msn][]=NUETBUS&start={prod_start_year}&end={prod_end_year}&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=100"
genUnitsURL = f"https://api.eia.gov/v2/total-energy/data/?api_key={api_key}&frequency=annual&data[0]=value&facets[msn][]=NUGBPUS&start={prod_start_year}&end={prod_end_year}&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=100"

In [3]:
data = requests.get(genUnitsURL).json()
nuclProductionData = requests.get(nuclProURL).json()

In [4]:
#print(data)

In [5]:
#print(json.dumps(data, indent = 4,sort_keys = True))

In [6]:
#number of Operating Nuclear Generators in US ANNUAL
df = pd.json_normalize(data['response'],'data')
df.head(10)

,period,msn,seriesDescription,value,unit
0,2022,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",94.659,Million Kilowatts
1,2021,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",95.546,Million Kilowatts
2,2020,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",96.501,Million Kilowatts
3,2019,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",98.119,Million Kilowatts
4,2018,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",99.433,Million Kilowatts
5,2017,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",99.629,Million Kilowatts
6,2016,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",99.565,Million Kilowatts
7,2015,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",98.672,Million Kilowatts
8,2014,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",98.569,Million Kilowatts
9,2013,NUGBPUS,"Nuclear Generating Units, Net Summer Capacity,...",99.240,Million Kilowatts

In [8]:
#export as csv
#df.to_csv('operatingunits.csv',encoding='utf-8')

In [9]:
#number of Nuclear Electric Power Produced Annually
nuclProd_df = pd.json_normalize(nuclProductionData['response'],'data')
nuclProd_df.head(10)

,period,msn,seriesDescription,value,unit
0,2022,NUETBUS,Nuclear Electric Power Consumption/Production ...,8061.020,Trillion Btu
1,2021,NUETBUS,Nuclear Electric Power Consumption/Production ...,8130.913,Trillion Btu
2,2020,NUETBUS,Nuclear Electric Power Consumption/Production ...,8251.075,Trillion Btu
3,2019,NUETBUS,Nuclear Electric Power Consumption/Production ...,8451.852,Trillion Btu
4,2018,NUETBUS,Nuclear Electric Power Consumption/Production ...,8438.068,Trillion Btu
5,2017,NUETBUS,Nuclear Electric Power Consumption/Production ...,8418.968,Trillion Btu
6,2016,NUETBUS,Nuclear Electric Power Consumption/Production ...,8426.753,Trillion Btu
7,2015,NUETBUS,Nuclear Electric Power Consumption/Production ...,8336.886,Trillion Btu
8,2014,NUETBUS,Nuclear Electric Power Consumption/Production ...,8337.559,Trillion Btu
9,2013,NUETBUS,Nuclear Electric Power Consumption/Production ...,8244.433,Trillion Btu